services:
  init:
    image: grafana/tempo:latest
    user: root
    entrypoint:
      - chown
      - '10001:10001'
      - /var/tempo
    volumes:
      - ./tempo-data:/var/tempo
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.128.0
    container_name: otel-collector
    volumes:
      - ./otel-config.yaml:/etc/otelcol-contrib/config.yaml
      - ${LOG_PATH}:/logs
    ports:
      - '8888:8888'
      - '8889:8889'
      - '4317:4317'
      - '4318:4318'
    command:
      - '--config=/etc/otelcol-contrib/config.yaml'
    networks:
      - observability
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prom-config.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'
    networks:
      - observability
    mem_limit: 512m
  tempo:
    image: grafana/tempo:latest
    command:
      - '-config.file=/etc/tempo.yaml'
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
      - ./tempo-data:/var/tempo #tmp?
    ports:
      - '3200'
      - '4317'
    depends_on:
      - init
    networks:
      - observability
    mem_limit: 512m
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - '3100:3100'
    command:
      - '-config.file=/etc/loki/local-config.yaml'
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
    networks:
      - observability
    mem_limit: 512m
  grafana:
    image: grafana/grafana:12.0.0
    volumes:
      - >-
        ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor metricsSummary
      - >-
        GF_INSTALL_PLUGINS=https://storage.googleapis.com/integration-artifacts/grafana-exploretraces-app/grafana-exploretraces-app-latest.zip;grafana-traces-app
    ports:
      - '3002:3000'
    networks:
      - observability
networks:
  observability: null
