global:
  scrape_interval: 30s
  evaluation_interval: 30s
scrape_configs:
  - job_name: otel-collector
    static_configs:
      - targets:
          - otel-collector:8889
storage:
  tsdb:
    min-block-duration: 2h
    max-block-duration: 2h
    retention:
      time: 1d
